### ISSUE TITLE
hangs in read-string on backquote

### ISSUE THREAD

**Issue by miner** [fogus/himera#22]
I tried this...
cljs.user> (cljs.reader/read-string "`foo") 

Himera never responded.

The following worked fine:

(cljs.reader/read-string "foo")
foo
cljs.user> (cljs.reader/read-string "@foo")
(deref foo)
cljs.user> (cljs.reader/read-string "'foo")
(quote foo)

**Comment by jaredly** [comment]
This now gives the following error:
```
Error: Reader for ` not implemented yet
    at Error (native)
    at cljs.reader.reader_error.a (http://localhost:4432/js/repl.js:18278:33)
    at cljs.reader.reader_error.b (http://localhost:4432/js/repl.js:18282:14)
    at cljs.reader.not_implemented (http://localhost:4432/js/repl.js:18394:35)
    at cljs.reader.read (http://localhost:4432/js/repl.js:18515:37)
    at cljs.reader.read_string (http://localhost:4432/js/repl.js:18525:27)
    at eval (eval at execute (webpack:///../plugins/itreed-js/exec.js?), <anonymous>:1:25)
    at eval (native)
```

I'd say this can be closed -- it's in cljs's domain, not himera's

**Comment by miner** [comment]
agreed
